[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn crypto_platform.wsgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "crypto_platform.railway_settings"
DEBUG = "False"
PYTHON_VERSION = "3.9.0"

[[services]]
name = "crypto-platform"

[services.variables]
PAYSTACK_SECRET_KEY = ""
PAYSTACK_PUBLIC_KEY = ""
